version: '3.8'

services:
  # API Service
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: interviewsfirst-api
    environment:
      - NODE_ENV=development
      - PORT=3001
      # Add your Neon database URL here
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_DISABLED=true
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - ADZUNA_APP_ID=${ADZUNA_APP_ID}
      - ADZUNA_APP_KEY=${ADZUNA_APP_KEY}
      - JOOBLE_API_KEY=${JOOBLE_API_KEY}
      # Enterprise-grade CORS configuration
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000,http://127.0.0.1:3001
    ports:
      - "3001:3001"
    volumes:
      - ./apps/api/uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Web Service
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: interviewsfirst-web
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://api:3001
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  uploads:
