version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: interview-me-postgres
    environment:
      POSTGRES_DB: jobplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - interview-me-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: interview-me-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - interview-me-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  interview-me-network:
    driver: bridge 