apiVersion: apps/v1
kind: Deployment
metadata:
  name: interviewsfirst-api
  namespace: staging
  labels:
    app: interviewsfirst-api
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: interviewsfirst-api
  template:
    metadata:
      labels:
        app: interviewsfirst-api
        environment: staging
    spec:
      containers:
      - name: api
        image: ghcr.io/interviewsfirst/interview-me/api:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: interviewsfirst-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: interviewsfirst-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: interviewsfirst-secrets
              key: jwt-secret
        - name: CORS_ORIGIN
          value: "https://staging.interviewsfirst.com"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: interviewsfirst-uploads-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: interviewsfirst-api-service
  namespace: staging
spec:
  selector:
    app: interviewsfirst-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: interviewsfirst-uploads-pvc
  namespace: staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
