apiVersion: apps/v1
kind: Deployment
metadata:
  name: interviewsfirst-web
  namespace: staging
  labels:
    app: interviewsfirst-web
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: interviewsfirst-web
  template:
    metadata:
      labels:
        app: interviewsfirst-web
        environment: staging
    spec:
      containers:
      - name: web
        image: ghcr.io/interviewsfirst/interview-me/web:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          value: "https://staging-api.interviewsfirst.com"
        - name: NEXT_PUBLIC_APP_URL
          value: "https://staging.interviewsfirst.com"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: interviewsfirst-web-service
  namespace: staging
spec:
  selector:
    app: interviewsfirst-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
